name: making diagram after main changes
on:
  push:
    branches:
    - main

jobs:
  make_diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
            output_file: "images/diagram.svg"
            excluded_paths: "dist,node_modules"
