name: making diagram after main changes
on:
  push:
    branches:
    - main

jobs:
  make_diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Update diagram
        id: make_diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "output-diagram.svg"
          artifact_name: "diagram"
          should_push: false
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: "diagram"
          path: "downloads"
